all:
	gcc -Wall -pedantic -std=c99 main.c execute.c piping.c redirection.c history.c -Iinclude -o CIS3110sh 

noC99:
	gcc -Wall -pedantic  main.c execute.c piping.c redirection.c history.c -Iinclude -o CIS3110sh 

noFlags:
	gcc -Wall  main.c execute.c piping.c redirection.c history.c -Iinclude -o CIS3110sh 
